// Single source of truth for blog post metadata. The RSS feed
// (src/app/rss.xml/route.ts), the sitemap (src/app/sitemap.ts), the blog
// index (src/app/blog/page.tsx), and each post's Article JSON-LD all read
// from this list, so adding or editing a post here updates every surface
// at once. Newest first - this is the display order on /blog.
//
// When you meaningfully edit a post, bump its dateModified: search engines
// use it for freshness signals in the Article schema and sitemap.

export type BlogPost = {
  slug: string
  title: string
  description: string
  /** ISO date the post first went live. */
  datePublished: string
  /** ISO date of the last meaningful content edit. */
  dateModified: string
  readTime: string
  tag: string
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'ai-detection-vs-plagiarism-checkers',
    title: 'AI Detection vs Plagiarism Checkers: What Is the Difference?',
    description: 'AI detectors and plagiarism checkers look for completely different things. Here is what each one actually catches, and why passing one says nothing about the other.',
    datePublished: '2026-07-08',
    dateModified: '2026-07-08',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'how-to-avoid-false-ai-detection',
    title: 'Wrongly Flagged as AI? Here Is What to Do',
    description: 'If an AI detector flagged writing you did yourself, you are not alone, and it does not mean you did anything wrong. Here is why it happens and how to handle it.',
    datePublished: '2026-07-08',
    dateModified: '2026-07-08',
    readTime: '7 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'how-to-reduce-ai-token-costs',
    title: 'How to Reduce AI Token Costs Without Losing Quality',
    description: 'Cut what you spend on AI without cutting corners. Simple ways to lower token use in your prompts and conversations, explained in plain English.',
    datePublished: '2026-07-08',
    dateModified: '2026-07-08',
    readTime: '7 min read',
    tag: 'Tokens',
  },
  {
    slug: 'what-is-a-context-window',
    title: 'What Is a Context Window? Why AI Forgets Things',
    description: 'AI can only "see" so much text at once. Here is what a context window is, why long chats trail off, and how to work with the limit instead of against it.',
    datePublished: '2026-07-08',
    dateModified: '2026-07-08',
    readTime: '6 min read',
    tag: 'Tokens',
  },
  {
    slug: 'why-does-ai-have-token-limits',
    title: 'Why Does AI Have Token Limits? (And What to Do About It)',
    description: 'Every AI tool has a limit on how much text it can handle at once. Here is why the limit exists, what happens when you hit it, and how to work around it.',
    datePublished: '2026-07-08',
    dateModified: '2026-07-08',
    readTime: '6 min read',
    tag: 'Tokens',
  },
  {
    slug: 'how-to-improve-a-prompt-score',
    title: 'How to Improve a Prompt Score (Without Overthinking It)',
    description: 'A low prompt score usually comes down to one or two missing pieces, not a bad idea. Here is how to raise your score fast, with real before-and-after examples.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'prompt-analyzer-guide',
    title: 'Prompt Analyzer Guide: How to Use It Well',
    description: 'A walkthrough of the Deepclario prompt analyzer: what it checks, how to read the results, and how to use it so your prompts actually get better over time.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'deep-rewrite-vs-standard-rewrite',
    title: 'Deep Rewrite vs Standard Rewrite: Which One Do You Need?',
    description: 'Standard rewrite fixes the obvious problems in a prompt fast. Deep rewrite digs deeper for prompts that really matter. Here is how to tell which one a task actually needs.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Product',
  },
  {
    slug: 'why-prompt-improvement-matters',
    title: 'Why Prompt Improvement Matters More Than People Think',
    description: 'A few minutes spent improving a prompt saves far more time than it costs, across every reply you get. Here is why prompt improvement pays off, with real numbers.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'prompt-quality-checklist',
    title: 'Prompt Quality Checklist: 9 Things to Check Before You Hit Send',
    description: 'A quick checklist to run your prompt through before sending it: goal, audience, format, limits, and a few things people forget. Bookmark it and check any prompt in under a minute.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '5 min read',
    tag: 'Prompting',
  },
  {
    slug: 'prompt-score-explained',
    title: 'Prompt Score Explained: What Your Prompt Rating Means',
    description: 'A prompt score rates how clear and complete your prompt is, from 0 to 100. Here is what the number measures, why it matters, and how to read each part.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'Prompting',
  },
  {
    slug: 'what-is-artificial-intelligence',
    title: 'What Is Artificial Intelligence? A Simple Guide for Beginners',
    description: 'Artificial intelligence is software that learns patterns and makes guesses instead of following fixed rules. Here is what AI really is, in plain English, with everyday examples.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '8 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'machine-learning-explained',
    title: 'Machine Learning Explained: A Simple Guide for Beginners',
    description: 'Machine learning is software that learns from examples instead of following rules. Here is what it is, how it works, and where you meet it, in plain English.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '8 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'how-ai-predicts-words',
    title: 'How AI Predicts Words: The Simple Idea Behind Chatbots',
    description: 'AI writes by guessing the next word, one at a time. Here is how that works in plain English, why it explains so much AI behavior, and where it goes wrong.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '8 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'how-chatbots-work',
    title: 'How Do AI Chatbots Work? A Simple Explanation',
    description: 'AI chatbots like ChatGPT read your message, break it into small pieces, and predict a reply one word at a time. Here is the whole process in plain English.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'how-ai-learns-language',
    title: 'How Does AI Learn Language? A Simple Explanation',
    description: 'AI learns language by reading a huge amount of text and practicing guessing the next word, over and over. Here is how that turns into fluent writing, in plain English.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'why-ai-makes-mistakes',
    title: 'Why Does AI Make Mistakes? Hallucinations Explained Simply',
    description: 'AI makes confident mistakes because it predicts words that sound right, not words it has checked. Here is why AI hallucinations happen and how to protect yourself.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'embeddings-explained',
    title: 'Embeddings Explained: How AI Turns Words Into Numbers',
    description: 'Embeddings are how AI turns words into numbers so it can measure which ones are related. Here is what embeddings are, in plain English, with everyday examples.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'ai-glossary-for-beginners',
    title: 'AI Glossary for Beginners: 30 Terms Explained Simply',
    description: 'A plain-English AI glossary. Clear, jargon-free definitions of the AI terms you keep seeing, from tokens and prompts to hallucinations and large language models.',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    readTime: '9 min read',
    tag: 'AI Basics',
  },
  {
    slug: 'are-ai-detectors-accurate',
    title: 'Are AI Detectors Accurate? What They Can and Cannot Tell You',
    description: 'AI detectors are useful but not proof. Here is how accurate they really are, when to trust the score, and when a result should not decide anything on its own.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'ai-detector-false-positives',
    title: 'AI Detection False Positives: Why Human Writing Gets Flagged',
    description: 'A false positive is when an AI detector flags human writing as AI. Here is why it happens, who it hits most, and how to avoid acting on a wrong result.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'what-ai-detectors-look-for',
    title: 'What AI Detectors Look For in Writing',
    description: 'AI detectors do not read for meaning. They look for a few specific patterns in the writing. Here is exactly what they measure, in plain terms.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'can-ai-detectors-be-fooled',
    title: 'Can AI Detectors Be Fooled? An Honest Answer',
    description: 'Yes, AI detectors can be fooled, and it is easier than people think. Here is how it happens, why it matters, and what it means for anyone relying on a score.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'ai-detection-score-explained',
    title: 'AI Detection Score Explained: What the Percentage Means',
    description: 'What does a "78% AI" score actually mean? Here is how to read an AI detection score, what the number does and does not tell you, and how to act on it.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '5 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'detect-chatgpt-claude-gemini-text',
    title: 'Can You Detect Text from ChatGPT, Claude, and Gemini?',
    description: 'Does the AI model change whether a detector can spot the text? Here is why detection works the same for ChatGPT, Claude, and Gemini, and where each one differs.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'human-text-vs-ai-text',
    title: 'Human Text vs AI Text: What Actually Differs',
    description: 'What really separates human writing from AI writing? Here are the real differences in rhythm, surprise, and voice, and why the line is blurrier than it looks.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'ai-detection-for-teachers',
    title: 'AI Detection for Teachers: A Fair Way to Use It',
    description: 'AI detectors can help teachers, but they cause harm when used as proof. Here is a fair, practical way to use detection in a classroom without wrongly accusing students.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'ai-detection-for-recruiters',
    title: 'AI Detection for Recruiters and Hiring',
    description: 'AI-written cover letters and applications are everywhere. Here is how recruiters can use AI detection fairly, what it misses, and why it should never auto-reject.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'ai-detection-in-universities',
    title: 'AI Detection in Universities and Schools',
    description: 'How schools and universities use AI detection, where it goes wrong at scale, and what a fair academic-integrity policy looks like when detectors are involved.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'chain-of-thought-prompting',
    title: 'Chain-of-Thought Prompting Explained (With Examples)',
    description: 'Chain-of-thought prompting asks the AI to reason step by step before answering. Here is what it is, when it helps, and how to use it, with clear examples.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'role-prompting-examples',
    title: 'Role Prompting: Examples That Improve AI Answers',
    description: 'Role prompting tells the AI who to be before it answers. Here is how it changes the output, with ready-to-use examples for writing, coding, and advice.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'prompt-structure-that-gets-better-results',
    title: 'Prompt Structure That Gets Better Results',
    description: 'The order you put things in a prompt changes the answer. Here is a simple prompt structure, in five parts, that gets clearer results from any AI model.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'how-context-improves-ai-responses',
    title: 'How Context Improves AI Responses (With Examples)',
    description: 'The AI cannot see your situation. Context is how you tell it. Here is what context to add to a prompt, and how it turns generic answers into useful ones.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'prompt-length-vs-response-quality',
    title: 'Prompt Length vs Response Quality: Does Longer Help?',
    description: 'A longer prompt is not always a better prompt. Here is how prompt length really affects AI response quality, and when adding more actually hurts.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '5 min read',
    tag: 'Prompting',
  },
  {
    slug: 'how-to-test-a-prompt',
    title: 'How to Test a Prompt: A Simple Method',
    description: 'A good prompt is one you have tested, not one you hoped would work. Here is a simple way to test a prompt, spot where it breaks, and fix it before you rely on it.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'how-to-compare-ai-prompts',
    title: 'How to Compare Two AI Prompts (And Pick the Better One)',
    description: 'Which prompt is better? Guessing does not work. Here is a fair way to compare two AI prompts side by side and pick the one that really performs.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '5 min read',
    tag: 'Prompting',
  },
  {
    slug: 'how-to-optimize-a-prompt',
    title: 'How to Optimize a Prompt, Step by Step',
    description: 'Optimizing a prompt is not guesswork. Here is a clear step-by-step method to turn a rough prompt into one that gets reliable results, one change at a time.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Prompting',
  },
  {
    slug: 'why-most-prompts-fail',
    title: 'Why Most AI Prompts Fail (And How to Fix Yours)',
    description: 'Bad AI results usually come from the prompt, not the model. Here are the four reasons prompts fail, with a weak and strong version of each so you can fix yours.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'Prompting',
  },
  {
    slug: 'word-vs-token-how-ai-counts-text',
    title: 'Word Count vs Token Count: Why AI Counts Text Differently',
    description: 'AI models count text in tokens, not words. This guide shows the difference, gives a simple words-to-tokens rule, and explains why the two rarely match.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Tokens',
  },
  {
    slug: 'what-is-a-token-in-ai',
    title: 'What Is a Token in AI? A Plain-English Explanation with Examples',
    description: 'A token is the small chunk of text an AI model actually reads. Not a word, not a letter. Here is what tokens are, with real examples you can check yourself.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '6 min read',
    tag: 'Tokens',
  },
  {
    slug: 'how-ai-detectors-work',
    title: 'How AI Detectors Work: A Clear Guide to Accuracy and Limits',
    description: 'AI detectors guess whether text was written by a machine by measuring how predictable it is. Learn how they work, how accurate they are, and where they fail.',
    datePublished: '2026-07-06',
    dateModified: '2026-07-07',
    readTime: '7 min read',
    tag: 'AI Detection',
  },
  {
    slug: 'what-is-deep-rewrite',
    title: 'What is Deep Rewrite? How the Pro Rewrite Mode Works',
    description: 'Deep Rewrite makes a stronger model draft your improved prompt, critique its own draft, then refine it before you see it. Here is exactly what you get compared to the normal rewrite.',
    datePublished: '2026-07-03',
    dateModified: '2026-07-03',
    readTime: '5 min read',
    tag: 'Product',
  },
  {
    slug: 'what-is-prompt-engineering',
    title: 'What is Prompt Engineering? A Complete Guide for Beginners',
    description: 'Prompt engineering is the practice of writing structured instructions for AI models to get better, more reliable results. Learn the fundamentals and key techniques.',
    datePublished: '2026-04-01',
    dateModified: '2026-04-28',
    readTime: '8 min read',
    tag: 'Guide',
  },
  {
    slug: 'how-to-write-better-prompts',
    title: 'How to Write Better AI Prompts - 7 Proven Techniques',
    description: '7 practical techniques to write better prompts for ChatGPT, Claude, and Gemini. Includes real before and after examples for each technique.',
    datePublished: '2026-04-01',
    dateModified: '2026-04-28',
    readTime: '7 min read',
    tag: 'Techniques',
  },
  {
    slug: 'chatgpt-prompt-tips',
    title: '10 ChatGPT Prompt Tips That Actually Work',
    description: 'Most ChatGPT users get mediocre results because their prompts are too vague. These 10 practical tips will immediately improve what you get back.',
    datePublished: '2026-04-01',
    dateModified: '2026-04-29',
    readTime: '6 min read',
    tag: 'Tips',
  },
  {
    slug: 'prompt-engineering-examples',
    title: 'Prompt Engineering Examples - Real Before and After Prompts',
    description: 'Real prompt engineering examples with before and after comparisons across writing, coding, research, and business use cases.',
    datePublished: '2026-04-01',
    dateModified: '2026-04-29',
    readTime: '9 min read',
    tag: 'Examples',
  },
  {
    slug: 'what-is-a-good-prompt',
    title: 'What Makes a Good AI Prompt? 5 Things Every Strong Prompt Has',
    description: 'A good AI prompt has five elements: goal clarity, context, format specification, constraints, and examples. Here is what each one means in practice.',
    datePublished: '2026-04-01',
    dateModified: '2026-04-29',
    readTime: '5 min read',
    tag: 'Fundamentals',
  },
  {
    slug: 'best-chatgpt-prompts-for-work',
    title: 'Best ChatGPT Prompts for Work (2026)',
    description: 'Ready-to-use ChatGPT prompts for emails, meeting notes, job descriptions, performance reviews, and SWOT analysis. Copy, fill in the blanks, get results.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '7 min read',
    tag: 'Templates',
  },
  {
    slug: 'how-to-use-chatgpt-for-writing',
    title: 'How to Use ChatGPT for Writing - A Practical Guide',
    description: 'How to use ChatGPT for writing without sounding like a robot. Covers blog posts, emails, stories, and marketing copy with real examples.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '8 min read',
    tag: 'Guide',
  },
  {
    slug: 'how-to-get-better-results-from-chatgpt',
    title: 'How to Get Better Results from ChatGPT - 8 Techniques',
    description: '8 techniques that fix the most common reasons people get mediocre ChatGPT output. Each one with a weak vs. strong prompt example.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '8 min read',
    tag: 'Techniques',
  },
  {
    slug: 'claude-ai-prompts',
    title: 'Claude AI Prompts - How to Write Better Prompts for Claude',
    description: 'How Claude handles prompts differently from ChatGPT, what it excels at, and ready-to-use prompt examples optimized for Claude.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '7 min read',
    tag: 'Guide',
  },
  {
    slug: 'ai-prompt-best-practices',
    title: 'AI Prompt Best Practices - What Actually Works in 2026',
    description: 'Eight prompt best practices that consistently produce better output across ChatGPT, Claude, and Gemini. Not theory - actual techniques.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '7 min read',
    tag: 'Best Practices',
  },
  {
    slug: 'chatgpt-system-prompt-examples',
    title: 'ChatGPT System Prompt Examples - What They Are and How to Use Them',
    description: 'What system prompts are, how to set them in ChatGPT, and four ready-to-use system prompt examples for writing, coding, research, and strategy.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '7 min read',
    tag: 'Guide',
  },
  {
    slug: 'zero-shot-vs-few-shot-prompting',
    title: 'Zero-Shot vs Few-Shot Prompting - What the Difference Means in Practice',
    description: 'Zero-shot and few-shot prompting explained clearly. What each technique is, when to use which, and real examples showing how examples change output.',
    datePublished: '2026-05-01',
    dateModified: '2026-05-25',
    readTime: '6 min read',
    tag: 'Fundamentals',
  },
]

/** Look up a post by slug; throws at build time if a page references a slug missing from the registry. */
export function getBlogPost(slug: string): BlogPost {
  const post = BLOG_POSTS.find(p => p.slug === slug)
  if (!post) throw new Error(`Blog post "${slug}" is missing from BLOG_POSTS in src/lib/blog-posts.ts`)
  return post
}
