import type { Metadata } from 'next'
import Link from 'next/link'
import { DetectorClient } from './detector-client'
import { MarketingNav } from '@/components/marketing/MarketingNav'
import { defaultOGImage } from '@/lib/og-image'

export const metadata: Metadata = {
  // A title and an H1 have different jobs. The H1 is for somebody who has
  // already arrived, so plain wins. The title is for a results page full of
  // near-identical entries, where its job is to earn the click, and "Shows Its
  // Work" is the only thing on that SERP that separates us. Same split as the
  // homepage. The on-page copy stays plain.
  title: 'Free AI Text Detector - Shows Its Work',
  description:
    'Paste the text. We show you the signs we found. We never give a score out of 100, because nobody can.',
  alternates: { canonical: 'https://deepclario.com/detector' },
  openGraph: {
    title: 'AI Text Detector - Deepclario',
    description:
      'Honest, transparent AI-content detection. Burstiness, vocabulary diversity, AI-cliché density, and more - every signal shown openly.',
    url: 'https://deepclario.com/detector',
    type: 'website',
    // Pages with their own openGraph object need an explicit image - see
    // defaultOGImage() for why the file-convention fallback doesn't apply.
    images: defaultOGImage('AI Text Detector - Deepclario'),
  },
}

// Shared by the visible FAQ section and the FAQPage structured data, so
// the two never drift. Written to read naturally while covering the
// "AI text detector" search intent.
const DETECTOR_FAQ = [
  {
    q: 'What is an AI text detector?',
    a: 'An AI text detector estimates whether a passage was written by a person or generated by an AI model like ChatGPT, Claude, or Gemini. Deepclario’s AI text detector measures concrete signals - sentence-length burstiness, vocabulary diversity, and em-dash and cliché density - then sorts the text into three honest bands: likely human, mixed, or likely AI.',
  },
  {
    q: 'Is the AI text detector free?',
    a: 'Yes. You can run one detection free with no account. A free Deepclario account raises that to five texts every 24 hours, and Pro removes the limit entirely.',
  },
  {
    q: 'Can it detect ChatGPT, Claude, and Gemini text?',
    a: 'Yes. The detector looks for the statistical fingerprints common to modern large language models, so it works on writing from ChatGPT, Claude, Gemini, and most other AI tools.',
  },
  {
    q: 'How accurate is AI content detection?',
    a: 'No AI detector is perfect - every tool has a false-positive rate, and detectors often misflag non-native English writing. That is why Deepclario never shows a made-up percentage. It shows the raw signals and a confidence band so you can judge the text yourself.',
  },
]

const detectorSchema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'WebApplication',
      name: 'Deepclario AI Text Detector',
      url: 'https://deepclario.com/detector',
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      description:
        'A free, transparent AI text detector that shows the burstiness, vocabulary, and cliché signals behind every verdict instead of an invented percentage.',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      publisher: { '@id': 'https://deepclario.com/#organization' },
    },
    {
      '@type': 'FAQPage',
      mainEntity: DETECTOR_FAQ.map(f => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    },
  ],
}

/**
 * THE PUBLIC DETECTOR. Prerendered, indexable, marketing nav, no auth read.
 *
 * It used to serve both audiences: it read the session and rendered the app
 * shell for signed-in visitors. That cost the page its static rendering, and
 * it meant one route had to decide the shell for itself, which is the exact
 * shape AppFrame's comment warns about (History vanished from the sidebar on
 * this page for that reason).
 *
 * It is now split the way / and /check already are: the public marketing page
 * lives here and keeps the URL, its search rankings and its SEO section, and
 * /detect is the signed-in view inside the app shell. The sidebar points at
 * /detect. Nothing redirects, so every existing link and ranking to /detector
 * is untouched.
 */
export default function DetectorPage() {
  const mainContent = (
    <main className="pt-28 md:pt-36 pb-16 px-6 md:px-10">
      <div className="max-w-3xl mx-auto">
        {/* Marketing hero. One headline, one line, then the tool. The eyebrow
            is gone: it was a keyword, not a sentence anyone needed. */}
        <div>
          <h1
            className="display text-4xl md:text-[3.75rem] leading-[1.05] tracking-tight"
            style={{ color: 'var(--ink)' }}
          >
            Was this written{' '}
            <span className="accent">by a machine?</span>
          </h1>
          <p
            className="mt-4 md:mt-5 text-lg md:text-xl leading-relaxed max-w-2xl"
            style={{ color: 'var(--ink-soft)' }}
          >
            Paste the text. We show you the signs we found.
          </p>
        </div>

        <div className="mt-10 md:mt-12">
          <DetectorClient />
        </div>

        {/* Slim honesty note - narrow footer, not a section. */}
        <p
          className="mt-14 pt-5 text-xs leading-relaxed"
          style={{ borderTop: '1px solid var(--color-rule)', color: 'var(--color-paper-mute)' }}
        >
          We never give a score out of 100. Nobody can. We show the signs we found and let you judge.
        </p>
      </div>
    </main>
  )

  return (
    <div
      className="editorial grain min-h-screen relative"
      style={{ background: 'var(--color-ink)', color: 'var(--color-paper)' }}
    >
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(detectorSchema) }}
      />
      <MarketingNav current="detector" />
      {mainContent}

      {/* SEO content - only on the public (anon) page. Gives the detector
          real, indexable depth for "AI text detector" intent and mirrors
          the FAQ used in the FAQPage structured data above. */}
      <section className="px-6 md:px-10 pb-20">
        <div className="max-w-3xl mx-auto space-y-12">
          <div>
            <h2 className="font-serif text-2xl md:text-3xl mb-4 leading-tight" style={{ color: 'var(--color-paper)', fontWeight: 400 }}>
              How the AI text detector works
            </h2>
            <p className="text-base leading-[1.7]" style={{ color: 'var(--color-paper-mute)' }}>
              Most AI content detectors hand you a single percentage and hide the reasoning. Deepclario’s AI text detector does the opposite: it measures the concrete statistical signals that separate human writing from AI-generated text - sentence-length burstiness, vocabulary diversity, em-dash density, transition-word frequency, and common AI clichés - and shows you every number. Those signals are combined into three plain bands, likely human, mixed, or likely AI, so you always see the evidence behind the verdict.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-2xl md:text-3xl mb-4 leading-tight" style={{ color: 'var(--color-paper)', fontWeight: 400 }}>
              Is AI content detection accurate?
            </h2>
            <p className="text-base leading-[1.7]" style={{ color: 'var(--color-paper-mute)' }}>
              AI detection is not a solved problem, and any detector that claims otherwise is overselling. Independent testing shows paid detectors carry a 5–20% false-positive rate on human writing, and Stanford research found they flag non-native English speakers as AI roughly half the time. Deepclario treats detection as one signal among many: we never invent a confidence score, we surface the raw measurements, and we recommend reading the text yourself before drawing a conclusion.
            </p>
          </div>

          <div>
            <h2 className="font-serif text-2xl md:text-3xl mb-6 leading-tight" style={{ color: 'var(--color-paper)', fontWeight: 400 }}>
              AI text detector FAQ
            </h2>
            <div className="space-y-7">
              {DETECTOR_FAQ.map(f => (
                <div key={f.q}>
                  <h3 className="text-base md:text-lg mb-2" style={{ color: 'var(--color-paper)', fontWeight: 500 }}>
                    {f.q}
                  </h3>
                  <p className="text-base leading-[1.7]" style={{ color: 'var(--color-paper-mute)' }}>
                    {f.a}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <footer
        className="px-6 md:px-10 py-10"
        style={{ borderTop: '1px solid var(--color-rule)' }}
      >
        <div
          className="max-w-3xl mx-auto text-xs flex flex-wrap gap-x-4 gap-y-2"
          style={{ color: 'var(--color-paper-mute)' }}
        >
          <span>© 2026 Deepclario</span>
          <Link href="/" className="underline underline-offset-4" style={{ color: 'var(--color-paper)' }}>
            deepclario.com
          </Link>
          <Link href="/privacy" className="underline underline-offset-4" style={{ color: 'var(--color-paper)' }}>
            Privacy
          </Link>
        </div>
      </footer>
    </div>
  )
}
